### ISSUE TITLE
Nosetests for Latex write failing

### ISSUE THREAD

**Issue by taldcroft** [taldcroft/asciitable#11]
Commit 74d81a192b5a4ff47e00c360b68be77f8bfc313b introduced some issue that causes 4 failures on nosetest on linux (Python 2.4 and 2.7).  E.g. 

```
======================================================================
ERROR: test_write.test_write_table({'out': '\\begin{table}\n\\begin{center}\n\\caption{Mag values \\label{tab1}}\n\\begin{tabular}{|lcccccccccc|}\nID & XCENTER & YCENTER & MAG & MERR & MSKY & NITER & SHARPNESS & CHI & PIER & PERROR \\\\\n14 & 138.538 & 256.405 & 15.461 & 0.003 & 34.85955 & 4 & -0.032 & 0.802 & 0 & No_error \\\\\n18 & 18.114 & 280.17 & 22.329 & 0.206 & 30.12784 & 4 & -2.544 & 1.104 & 0 & No_error \\\\\n\\hline\n\\hline\n\\end{tabular}\n\\end{center}\n\\end{table}\n', 'kwargs': {'caption': 'Mag values \\label{tab1}', 'Writer': <class 'asciitable.latex.Latex'>, 'col_align': '|lcccccccccc|', 'latexdict': {'tablefoot': '\\end{center}', 'preamble': '\\begin{center}', 'data_end': ['\\hline', '\\hline']}}}, rec.array([ (14, 138.538, 256.405, 15.461, 0.003, 34.85955, 4, -0.032, 0.802, 0, 'No_error'),
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/cosmos2/ska/arch/x86_64-linux_CentOS-5/lib/python2.7/site-packages/nose-1.0.0-py2.7.egg/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/data/baffin/tom/git/asciitable/test/test_write.py", line 117, in check_write_table
    asciitable.write(table, out, **test_def['kwargs'])
  File "/data/baffin/tom/git/asciitable/asciitable/ui.py", line 243, in write
    lines = writer.write(table)
  File "/data/baffin/tom/git/asciitable/asciitable/latex.py", line 264, in write
    return core.BaseReader.write(self, table=table)
  File "/data/baffin/tom/git/asciitable/asciitable/core.py", line 862, in write
    self.header.write(lines)
  File "/data/baffin/tom/git/asciitable/asciitable/latex.py", line 90, in write
    lines.append(r'\begin{' + self.latex['tabletype'] + r'}')
KeyError: 'tabletype'
```

**Comment by hamogu** [comment]
The problem happens, because I moved the default for tabletype 
from the **init** into the call parameters. Thus, if a latexdict without key 'tabletye' is passed in, it fails. I though about it for a while, but I think this should be a bug, not a feature.
I have patched it and will send you a pull request shortly.
