### ISSUE TITLE
Different behaviour when numpy is present

### ISSUE THREAD

**Issue by jean** [taldcroft/asciitable#5]
When I run it where NumPy is installed, things fail:

```
>>> def out2csv(outfile, csvfile):
...     at = asciitable.read(outfile,
...            delimiter='|',
...            header_start=9,
...            data_start=11,
...            data_end=-4,
...            guess=False)
...     w = csv.writer(csvfile)
...     w.writerow(at.dtype.names[1:-1])
...     w.writerows([list(l)[1:-1] for l in at])
...     csvfile.close()
...     print csvfile.name
...
>>> for fn in fns:
...   csvfile = fn.replace('out', 'csv')
...   csvfile = open(csvfile, 'w')
...   out2csv(fn, csvfile)
...
Traceback (most recent call last):
  File "<stdin>", line 4, in ?
  File "<stdin>", line 7, in out2csv
  File "build/bdist.linux-i686/egg/asciitable.py", line 912, in read
  File "build/bdist.linux-i686/egg/asciitable.py", line 745, in read
  File "build/bdist.linux-i686/egg/asciitable.py", line 665, in __call__
  File "/usr/lib/python2.4/site-packages/numpy/core/records.py", line 502, in fromarrays
    parsed = format_parser(formats, names, titles, aligned, byteorder)
  File "/usr/lib/python2.4/site-packages/numpy/core/records.py", line 113, in __init__
    self._setfieldnames(names, titles)
  File "/usr/lib/python2.4/site-packages/numpy/core/records.py", line 161, in _setfieldnames
    raise ValueError, "Duplicate field names: %s" % _dup
ValueError: Duplicate field names: ['']
```

With the same data, without NumPy, it works fine. 
This is using asciitable-0.5.1-py2.4.egg

**Comment by jean** [comment]
The data starts as follows:

```
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> +--------------------+--------------------+-------------------------+--------------------+--------------------+--------------------+--------------------------+--------------------+--------------------+---------------------------------------------------------------------------------+------------+------------+------------+------------------+------------+
| ldgb_f_fnlp_fscl_yr| ldgb_f_fund_id_code| orgu_f_orgu_dept_id_code| ldgb_f_orgu_id_code| ldgb_f_pgmm_id_code| ldgb_f_proj_id_code| ldgb_proj_external_symbol| ldgb_f_objc_id_code| ldgb_f_objt_id_code| budg_line_descr                                                                 | allotment  | unliq_oblig| disbursment| total_expenditure| balance    |
+--------------------+--------------------+-------------------------+--------------------+--------------------+--------------------+--------------------------+--------------------+--------------------+---------------------------------------------------------------------------------+------------+------------+------------+------------------+------------+
| 2010               | FPL                | 2230                    | 5020               |                    | 1213               | 1213M000                 | 441                | 160100             |                                                                                 | 0          | 2499       | 0          | 2499             | -2499      |
```

**Comment by taldcroft** [comment]
The root of the problem is that the data file is parsed as having two empty columns, one before the first "|" and one after the last "|".  This is just a consequence of defining "|" as the delimiter _between_ columns.  So there are two columns that are named "" (empty string).  The non-NumPy outputter isn't bothered by identical column names (though that is probably a bug in itself), while the NumPy outputter fails within NumPy numpy.rec.fromarrays().  A NumPy record array requires unique column names.

This is a common problem with bar "|" delimited files because often there is a bar at the beginning and end.  I'll think about an enhancement to make this situation easier.  In the meantime something like the following should work:

```
lines = [x.strip()[1:-1] for x in open(outfile).readlines()]
at = asciitable.read(lines, ....)
```
